Repository AtomLinter/linter-eslint, pull requests merged in 2021-03, with the labels that each got.

#1358 add activation hook
  package.json
  spec/linter-eslint-spec.js
Labels: performance

#1393 ci: use GitHub Actions
  .circleci/config.yml
  .github/workflows/CI.yml
  .github/workflows/bump_deps.yml
  .npmrc
  .travis.yml
  appveyor.yml
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: chore, ci, tests

#1371 Global Eslint improvements
  .github/workflows/CI.yml
  package.json
  spec/worker-helpers-spec.js
  src/worker-helpers.js
Labels: bug

#1359 fix: expected a `length` to be non-negative error
  package.json
  pnpm-lock.yaml
  src/helpers.js
Labels: bug

#1407 improve Rules in src/rules.js
  src/rules.js
Labels: performance, refactor

#1411 chore: remove the dependencies that are already in the CI
  package.json
  pnpm-lock.yaml
Labels: dependencies

#1412 chore(ci): separate commitlint from lint
  .github/workflows/CI.yml
Labels: ci

#1408 fix(deps): update atom-package-deps
  .eslintignore
  package.json
  pnpm-lock.yaml
Labels: dependencies

#1068 Use getConfigForFile to handle configurations
  package.json
  spec/fixtures/configs/json/.eslintrc.json
  spec/fixtures/configs/json/foo.js
  spec/fixtures/configs/no-ext/.eslintrc
  spec/fixtures/configs/no-ext/foo.js
  spec/fixtures/configs/none/foo.js
  spec/fixtures/configs/package-json/foo.js
  spec/fixtures/configs/package-json/nested/foo.js
  spec/fixtures/configs/package-json/nested/package.json
  spec/fixtures/configs/package-json/package.json
  spec/fixtures/configs/yaml/.eslintrc.yaml
  spec/fixtures/configs/yaml/foo.js
  spec/fixtures/configs/yml/.eslintrc.yml
  spec/fixtures/configs/yml/foo.js
  spec/linter-eslint-spec.js
  spec/worker-helpers-spec.js
  src/is-config-at-home-root.js
  src/main.js
  src/worker-helpers.js
  src/worker.js
Labels: enhancement

#1415 fix: fix stackoverflow for fallbackForGlobal error
  spec/worker-helpers-spec.js
  src/worker-helpers.js
Labels: bug

#1416 fix: handle prettier line-ending issue
  src/helpers.js
Labels: bug

#1423 chore: update babel
  .eslintignore
  .github/workflows/CI.yml
  .gitignore
  babel.config.json
  package.json
  pnpm-lock.yaml
  rollup.config.js
  spec/linter-eslint-spec.js
  spec/migrate-config-options-spec.js
  spec/rules-spec.js
  spec/validate/editor-spec.js
  spec/validate/throw-spec.js
  spec/worker-helpers-spec.js
  src/helpers.js
  src/main.js
  src/migrate-config-options.js
  src/validate/editor.js
  src/validate/throw.js
  src/worker-helpers.js
  src/worker.js
Labels: chore, dependencies

#1424 fix: fix dynamic require errors
  package.json
  pnpm-lock.yaml
  rollup.config.js
Labels: dependencies

#1422 Improve the tests
  package.json
  pnpm-lock.yaml
  spec/fixtures/files/inline/badInline.js
  spec/fixtures/files/with-config/.eslintcache
  spec/fixtures/files/with-config/.eslintrc.js
  spec/fixtures/files/with-config/bad.js
  spec/fixtures/files/with-config/empty.js
  spec/fixtures/files/with-config/fix.js
  spec/fixtures/files/with-config/good.js
  spec/linter-eslint-spec.js
  spec/runner.js
  spec/worker-helpers-spec.js
  src/helpers.js
  src/main.js
Labels: tests
